### ISSUE TITLE
Build as a executable

### ISSUE THREAD

**Issue by NULLYUKI** [PrincessAkira/labydownloader#3]
To prevent extra steps of the user having to install NodeJS, it would be much better to build LabyDownloader as a executable.

#2 Was incorrectly closed, because it is apparently not possible according to https://github.com/PrincessAkira/labydownloader/issues/2#issuecomment-1720071306

**Comment by NULLYUKI** [comment]
@PrincessAkira Look https://nodejs.org/api/single-executable-applications.html

It is even a built in feature. Even though it is experimental, it is possible. So I have no idea why you claim this is not possible.
Like you claim you said the reason, but you didn't and I want the reason finally after literally months of waiting.

**Comment by HerXayah** [comment]
Bro stop annoying me fucking everywhere.
Stop spamming everything i have.
Stop creating useless commits. 
Dont ever interact with me again
